
    document.getElementById("ButtonPrograma1").addEventListener("click", function() {
        window.location.href = "Programa1.html";
    });


    document.getElementById("ButtonPrograma2").addEventListener("click", function() {
        window.location.href = "Programa2.html";
    });

    document.getElementById("ButtonPrograma3").addEventListener("click", function() {
        window.location.href = "Programa3.html";
    });

